import type { Block } from 'payload'
import { ctaFields } from '@/fields/ctaFields'

export const SLATable: Block = {
  slug: 'slaTable',
  interfaceName: 'SLATableBlock',
  labels: {
    singular: 'SLA / Response Time Table',
    plural: 'SLA / Response Time Tables',
  },
  fields: [
    {
      name: 'badge',
      type: 'text',
      label: 'Badge Text',
      defaultValue: 'SERVICE LEVEL AGREEMENT',
      localized: true,
    },
    {
      name: 'title',
      type: 'text',
      label: 'Title',
      required: true,
      localized: true,
    },
    {
      name: 'subtitle',
      type: 'textarea',
      label: 'Subtitle',
      localized: true,
    },
    {
      name: 'rows',
      type: 'array',
      label: 'Priority Rows',
      minRows: 1,
      maxRows: 6,
      fields: [
        {
          name: 'priority',
          type: 'select',
          label: 'Priority',
          options: [
            { label: 'High', value: 'High' },
            { label: 'Medium', value: 'Medium' },
            { label: 'Low', value: 'Low' },
          ],
          defaultValue: 'Medium',
          required: true,
        },
        {
          name: 'severity',
          type: 'select',
          label: 'Severity Color',
          options: [
            { label: 'Red', value: 'red' },
            { label: 'Amber', value: 'amber' },
            { label: 'Blue', value: 'blue' },
            { label: 'Green', value: 'green' },
          ],
          defaultValue: 'blue',
          required: true,
        },
        {
          name: 'impact',
          type: 'text',
          label: 'Impact Headline',
          admin: { description: 'Short label, e.g. "Complete System Outage".' },
          required: true,
          localized: true,
        },
        {
          name: 'impactExamples',
          type: 'array',
          label: 'Impact Examples (optional)',
          maxRows: 4,
          fields: [{ name: 'text', type: 'text', required: true, localized: true }],
          admin: { description: 'Concrete examples shown as bullets under the impact headline, e.g. "Core network, server, or firewall failure".' },
        },
        {
          name: 'remoteSupportTime',
          type: 'text',
          label: 'Remote Support Time',
          required: true,
          localized: true,
        },
        {
          name: 'remoteSupportNote',
          type: 'textarea',
          label: 'Remote Support Note (optional)',
          localized: true,
          admin: { description: 'Explains what happens during remote support, e.g. "Incident is prioritized immediately and remote troubleshooting begins without delay."' },
        },
        {
          name: 'onsiteSupportTime',
          type: 'text',
          label: 'Onsite Support Time',
          required: true,
          localized: true,
        },
        {
          name: 'onsiteSupportNote',
          type: 'textarea',
          label: 'Onsite Support Note (optional)',
          localized: true,
          admin: { description: 'Explains when onsite support is arranged, e.g. "Arranged when remote troubleshooting cannot restore service."' },
        },
        {
          name: 'helpdeskAvailability',
          type: 'text',
          label: 'Helpdesk Availability',
          required: true,
          localized: true,
        },
        {
          name: 'resolutionTarget',
          type: 'text',
          label: 'Resolution Target',
          required: true,
          localized: true,
        },
        {
          name: 'resolutionApproach',
          type: 'textarea',
          label: 'Resolution Approach (optional)',
          localized: true,
          admin: { description: 'Explains how that resolution target is actually approached, e.g. "Uninterrupted support until resolved or a workaround is live."' },
        },
      ],
    },
    ...ctaFields('Talk to Our Experts', 'Have questions about our SLA commitments?'),
  ],
}
