import type { IconPreset } from './icons'

/**
 * Best-guess icon per known service/sub-service title, used as a fallback when a
 * page doesn't have its own `icon` field set. Matched case-insensitively.
 */
const TITLE_ICON_MAP: Record<string, IconPreset> = {
  'it amc': 'smartphone',
  'on call it support': 'headset',
  'new office it setup': 'building',
  'it relocation': 'pin',
  'it outsourcing': 'handshake',
  'data recovery': 'refresh',
  'remote support': 'wrench',
  'desktop support': 'monitor',
  'it asset management': 'box',
  'server installation': 'server',
  'nas storage': 'database',
  'san storage': 'database',
  vmware: 'layout',
  'hyper v': 'layout',
  'virtual machines': 'box',
  'server rack installation': 'server',
  'environmental monitoring': 'chart',
  'security operations center (soc)': 'shield',
  'email security solution-on cloud': 'cloud',
  'vulnerability assessment and penetration testing': 'search',
  'cloud and network security': 'cloud',
  'services solution': 'shield',
  'endpoint protection, edr, xdr & mdr': 'shield',
  'secure email (s/mime)': 'lock',
  'web application firewall (waf)': 'shield',
  'data loss prevention solution': 'lock',
  'employee monitoring': 'users',
  'mobile device management': 'smartphone',
  'pam / pim solutions': 'lock',
  'sase solution': 'network',
  'siem solution': 'chart',
  'soar solution': 'settings',
  'intelligent threat detection': 'search',
  'anti spoofing and impersonation solution': 'shield',
  'lan and wan': 'network',
  vpn: 'lock',
  'enterprise wi-fi': 'wifi',
  'network optimization': 'settings',
  'internet load balancing': 'network',
  'cat6/cat6a cabling': 'network',
  'fiber optic cabling': 'network',
  'network rack installation': 'server',
  'data center cabling': 'database',
  'network monitoring': 'chart',
  'microsoft 365': 'cloud',
  'microsoft copilot': 'code',
  'dynamics 365': 'chart',
  'microsoft 365 security': 'shield',
  'microsoft sharepoint': 'document',
  'security consultation': 'lightbulb',
  'microsoft 365 migration': 'refresh',
  'microsoft azure': 'cloud',
  'aws cloud': 'cloud',
  'cloud migration': 'refresh',
  'cloud backup': 'database',
  'disaster recovery': 'refresh',
  'cloud security': 'shield',
  'google cloud': 'cloud',
  'local backup': 'database',
  'hybrid backup': 'refresh',
  'disaster recovery planning': 'document',
  'ransom recovery': 'shield',
  'business continuity': 'chart',
  'ip telephony': 'phone',
  'voip solutions': 'phone',
  'cloud pbx': 'cloud',
  'conference phones': 'headset',
  'call center solutions': 'headset',
  'contact center solutions': 'users',
  'call recording and ivr': 'mic',
  'collaboration displays': 'tv',
  'boardroom solutions': 'tv',
  'meeting room solutions': 'monitor',
  'interactive displays': 'tv',
  'digital signage': 'tv',
  'casting solutions': 'wifi',
  'smart classroom solutions': 'graduation',
  'video walls': 'tv',
  projectors: 'monitor',
  'public address(pa) solutions': 'mic',
  'background music': 'mic',
  'auditorium solutions': 'mic',
  'multi-room audio': 'mic',
  'speaker system': 'mic',
  'av consultation': 'lightbulb',
  'av programming': 'code',
  'av design services': 'layout',
  'smart building solutions': 'building',
  'cctv installations': 'camera',
  'ai cameras': 'camera',
  'access control and bio-metric attendance system': 'lock',
  'gate barrier and automations': 'settings',
  'intercom systems': 'phone',
  'visitor management system': 'users',
  'anpr systems': 'camera',
  servers: 'server',
  'desktop computers': 'monitor',
  'business laptops': 'box',
  workstations: 'monitor',
  printers: 'printer',
  'ups systems': 'box',
  routers: 'network',
  switches: 'network',
  firewalls: 'shield',
  'wireless access points': 'wifi',
  'network cabinets': 'box',
  'microsoft licensing': 'document',
  'adobe licensing': 'document',
  'antivirus licensing': 'shield',
  'windows licensing': 'document',
  'server licensing': 'document',
  'it consulting': 'lightbulb',
  'digital transformation': 'refresh',
  'infrastructure assessment': 'search',
  'cloud readiness assessment': 'cloud',
  'security assessment': 'shield',
  'site survey': 'pin',
  'solution design': 'layout',
  installation: 'box',
  configuration: 'settings',
  migration: 'refresh',
  commissioning: 'chart',
  'user training': 'graduation',
  'administrator training': 'graduation',
  documentation: 'document',
  'knowledge transfer': 'handshake',
}

export function getIconForServiceTitle(title?: string | null): IconPreset {
  if (!title) return 'wrench'
  return TITLE_ICON_MAP[title.trim().toLowerCase()] || 'wrench'
}
